title: Aplicaciones Web Interactivas con Shiny
author:
  name: Florencia D'Andrea
description: > # this means to ignore newlines until "show_excerpts:"
  Material del Taller de Shiny de LatinR 2020 y otras cosas más
show_excerpts: false # set to true to show excerpts on the homepage

theme: minima

layout: page
title: "PAGE TITLE"
permalink: /URL-PATH/
